### ISSUE TITLE
Feature Request: Ability to use an network address as source device.

### ISSUE THREAD

**Issue by xslushedx** [AxionDrak/GameCube-Backup-Manager#114]
If you have your backup isos on a NAS like me, it would be nice to be able to setup a network adress / share as source device.

**Comment by sjohnson1021** [comment]
Shouldn't be too hard.. I'm not sure but, can you not already use windows network shares if they're listed in explorer? Will look into different ways of implementing this.. Textbox (unc path) + button (enumerate) ? Build a list of locally defined shares from windows? Ideally, changing the open-file-dialog to more like the usual file picker with the address bar available? 

Suggestions on how you'd like to see it implemented?

**Comment by sjohnson1021** [comment]
And what about password protected shares?

**Comment by xslushedx** [comment]
My home server where I save my backups is displayed normally in Windows 10 explorer as a network device. The GameCube Backup Manager does not show any network related devices in the window where you can specify your source. I tried to mount a share as a network drive under Windows 10 but this is not displayed either. Sorry for my bad language, I can't describe it better.

**Comment by sjohnson1021** [comment]
> If you have your backup isos on a NAS like me, it would be nice to be able to setup a network adress / share as source device.

Assuming the share is already defined and accessible through explorer, this build has a button on the source tab next to the 'Tools' submenu, that will open the folder browser dialog to the 'Desktop' root folder, which will include Network locations as well as other weird symbolic links such as Control Panel.. Definitely not.. ideal, but. does function on windows shares and mapped network drives. 


I'm considering providing the option to just type the UNC path, as currently populating 'Network' takes far too long, because.. well, windows' network discovery function just chugs.

[gcbm-NAS-friendly.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/11043208/gcbm-NAS-friendly.zip)

**Comment by xslushedx** [comment]
With this new button I can easily reach my network shares and everything works fine. Thank you very much for that !!
