### ISSUE TITLE
Feature Request: CISO support

### ISSUE THREAD

**Issue by Linx-ESP** [AxionDrak/GameCube-Backup-Manager#117]
Using wimms WIT you can make compress games into a ciso file that nintendont support. Right now GCBM doesn't show them.

**Comment by sjohnson1021** [comment]
This is planned as part of the upcoming rewrite.. Probably going with Avalonia UI for cross-platform, as MAUI.. just isn't feeling like the best route. It essentially is Xamarin+, and would feel like running a mobile emulator on desktop..

I'm also looking at how to attempt replicating NKit's functionality(?) with repairing images using the fst and redump dats. Although, I'm not sure if that's something entirely neccessary, as NKit already exists. I guess I could see about bundling the files necessary to just pass information to the .exe's , what we are doing right now for scrubbing with GCIT. (Which I'm guessing is older than WIT... and not the best option to use?) 

I started contributing well after this project was established and functional, I've mainly been trying to go through and make optimizations, refactor the code to be more transferrable/easier to work with, and trying to make it more accessible. I fell out of the Wii scene around 2014, only occasionally jumping back in to do the occasional mod for family/friends. So my knowledge of what tools, and compression formats are best for what reasons. First I was hearing NKit was terrible, then great for long-hold libraries not meant for dolphin, then.. idk.



@laetemn had mentioned in the [Roadmap](https://github.com/AxionDrak/GameCube-Backup-Manager/wiki/Roadmap) that they're wanting to support:

> ## In Scope Features
> 
> The following features are currently planned. This list will change over time as features are implemented and new requests are approved.
> 
> + **Fix GameCube images with recovery fst and repair to match dats** (e.g. Redump)
> + Verify Task for checking internal file checksums
> + Rename image to match dat entry
> + Encryption / Decryption
> + Full support for ISO9660 Form2 sectors
> + Image building / modification (for modders)
> + Plus anything else people suggest that is a fit

Support for RVZ was also requested, although if @laetemn is wanting this to be more for physical hardware, and not emulation, that might not be made priority. I'll be honest. I'm a little green when it comes to byte-streams, offsets, pointers, and custom data-types. Like, I get the gist, I used to mess around with CheatEngine and other Memory Editors when I was younger, so I do know what they are, just new to working with that in code.

For .CISOs, obviously they are compressed, and a custom datatype, so without being able to view WIIM's source, or the file structure of a ciso (offsets, etc), I'm kind of drawing a blank how to approach this. I don't imagine you'd just be able to open it as a normal iso, So.. Do I just try and parse the byte-array?

**Comment by Linx-ESP** [comment]
This might be helpful, seems to be source code from WIT from 8 months ago, which matches its latest release:
https://github.com/Wiimm/wiimms-iso-tools
Would shipping GCBM with WIT included be useful? 

https://github.com/FIX94/Nintendont/issues/1004#issuecomment-1135983284 mentions they support "Hermes ISO" and that they are "sparse files, rather than _compressed_"
https://wit.wiimm.de/info/iso-images.html#ciso and https://wit.wiimm.de/wdf/ in case it is useful.
https://github.com/FIX94/Nintendont/pull/331/commits/8c7a64a331e9ac9e5e857e9f9f218332ee3fbb53 The commit that added support in Nintendont.

**Comment by sjohnson1021** [comment]
> This might be helpful, seems to be source code from WIT from 8 months ago, which matches its latest release:
> https://github.com/Wiimm/wiimms-iso-tools
👀... I swear I do know how to search... ... Wow, okay.. yeah, that would be exactly what I was looking for.

> Would shipping GCBM with WIT included be useful? 
> 
If I can't find a way to incorporate the code or rewrite it, then we'll probably ending up just calling the CLI behind the scenes like GCIT..
> https://github.com/FIX94/Nintendont/issues/1004#issuecomment-1135983284 mentions they support "Hermes ISO" and that they are "sparse files, rather than _compressed_"
> https://wit.wiimm.de/info/iso-images.html#ciso and https://wit.wiimm.de/wdf/ in case it is useful.
> https://github.com/FIX94/Nintendont/pull/331/commits/8c7a64a331e9ac9e5e857e9f9f218332ee3fbb53 The commit that added support in Nintendont.

Thank you, really. Cannot believe I missed his GitHub..

**Comment by sjohnson1021** [comment]
2.6.1.9 offers basic information reading from .ciso files (problems arise if any .ciso's have been renamed to .ISO) as well as transferring files. Scrub will reject .ciso and divert to normal 1:1 transfer on these files.

Will work on replacing GCIT with WIT and flesh out options for setting up the CLI arguments. Really need to attempt to start fresh, with a rewrite, however I'd like to utilize as much of the localization effort as possible, which will add additional time considerations.

**Comment by Linx-ESP** [comment]
https://wit.wiimm.de/info/iso-images.html#esc
With WIT you can do ``wit COPY/CONVERT (input file) --ciso (outputfolder)/%I/game.ciso``

This would output in the folder structure expected by Nintendont (I think newer versions or used via a launcher don't need `game.ciso`, any name it's ok)

**Comment by sjohnson1021** [comment]
Sweet, thanks, probably could've figured that out, but have been working on improving underlying systems (0 disrespect to Laete, but this project was initially designed in a largely monolith design. With 90% of the code being dumped into frmMain or partial forms extensions) Its taken a bit to migrate to a more modular approach to allow for systems like queuing, global notifications and settings, a modular task system to allow for new external executables and argument formats to be given (adding WIT with this argument pattern should now be trivial).

I very much appreciate you taking the time to abc that for me so I can just plug it into code. 

I promise updates are coming very soon. I've spent several nights not sleeping working on this (No particular reason, I'm just weird I guess and couldn't sleep anyway) broke several several systems in the process of .. well .. replacing them. But there's light at the end of the tunnel.. 

This might sound terrible, but I'm excited: 
I'm finally back to the same working feature set as before.. with some overdue fixes taken care of. But working with entirely different systems than before.

I'll work on adding WIT conversion, researching what arguments/settings would need to be addressed via UI elements to ensure we're utilizing WIT to the fullest, or at least cover the most common use cases.

After that, I think it's time to scrap the base, extract relevant code, and move to Avalonia, .Net Core, or some cross-platform alternative, and come at this with a fresh start. Once that's stable and covers the same functionality we are now (or will shortly), I'll try to work on adding NKit functionality, if it makes sense (they do have their own app, .. Soo?)

**Comment by Linx-ESP** [comment]
From https://gbatemp.net/threads/nintendont.349258/#InstallSD  

> The game path expected by Nintendont is :
> SD:/games/whatever you want/game.iso
> SD:/games/whatever you want/disc2.iso
> 
> The non-bold part need to be written exactly like you see it above (the filename is not the game's title, but the 4 letters "g+a+m+e")
> If a game has two discs, the second ISO needs to be placed in the same folder than the first disc's ISO, and named to "disc2.iso".
> Only the bold part "whatever you want" need to change.
> 
> For better compatibility with other loaders, you can put Game's Title and GameID in that part, like this :
> SD or USB:/games/Zelda Wind Waker [GZLP01]/game.iso
> SD or USB:/games/Tales of Symphonia [GQSEAF]/game.iso
> SD or USB:/games/Tales of Symphonia [GQSEAF]/disc2.iso
> 
> For users who still don't understand that "game" doesn't refer to the game's title but to the single word "game":
> /games/Zelda Wind Waker [GZLP01]/Zelda.iso <--- WRONG :hateit:
> /games/Zelda Wind Waker [GZLP01]/game.iso <--- Correct
> /games/Tales of Symphonia [GQSEAF]/disc2.iso <--- Correct
> 
> If you don't know the GameID, you don't need to use it.
> /games/zelda/game.iso is working too.


Seems that is the folder name is the one that doesn't need a particular name. With that said, nintendont documentation is _something_ and Loaders might change its path, but hopefully not.

===  

Good to see you are excited to work on this. Usually having to deal with others people code, even more if is somewhat old, is tiring.  
Hopefully once it gets a more modular approach it gets easier.
With that said, would something like [Prettier](https://prettier.io/) (but forC#) help with consistency and maybe even clearing visually some of the previous code?

**Comment by Linx-ESP** [comment]
From https://wit.wiimm.de/wit/#cmd
<html>
<body>


ID6 | ID | Print ID6 of all found ISO files as simple list.
-- | -- | --
ID8 |   | Print ID6 + 2 next bytes as disc and version number of all found ISO files as simple list.


</body>
</html>


Tested with Tales of Symphonia (2 discs) and Resident Evil 4 (2 discs + Bonus)
Command: `wit ID6 .\path-to-game` and `wit ID8 .\path-to-game` 
| Game | Disc | ID6 | ID8 |
| ---      | ---   | ---  | ---  |
| Tales of Symphnia (Spain) | Disc 1 | GQSSAF |  GQSSAF 00.00
| Tales of Symphnia (Spain) | Disc 2 | GQSSAF |  GQSSAF 01.00
| Resident Evil 4 (Europe) | Disc 1 | G4BP08 |  G4BP08 00.00
| Resident Evil 4 (Europe) | Disc 2 | G4BP08 |  G4BP08 01.00
| Resident Evil 4 (Europe) | Bonus Disc | D4BP01 | D4BP01 00.00

**Comment by sjohnson1021** [comment]
I very much appreciate you taking the time to abc that for me so I can just plug it into code.

I have been basically primary maintainer for this project for about almost a year now? But I've been in and out of hospital, and have had to take extended breaks. Coming back and.. attempting to remember what on earth I was working on before after a month or two in hospital here and there.

As for prettier, I ran the full project through SEVERAL automated cleanup and formatting tasks, at one point, and have several extensions for visual studio that cover that functionality on file save. And automated formatting/rule enforcement (task running? To do things like remove unused properties,check nulls, strong interpolations, etc.)  

I promise updates are coming very soon. I've spent several nights not sleeping working on this (No particular reason, I'm just weird I guess and couldn't sleep anyway) broke several several systems in the process of .. well .. replacing them. But there's light at the end of the tunnel.. 

This might sound terrible, but I'm excited: 
I'm finally back to the same working feature set as before.. with some overdue fixes taken care of. But working with entirely different systems than before.

I'll work on adding WIT conversion, researching what arguments/settings would need to be addressed via UI elements to ensure we're utilizing WIT to the fullest, or at least cover the most common use cases.

After that, I think it's time to scrap the base, extract relevant code, and move to Avalonia, .Net Core, or some cross-platform alternative, and come at this with a fresh start. Once that's stable and covers the same functionality we are now (or will shortly), I'll try to work on adding NKit functionality, if it makes sense (they do have their own app, .. Soo?)

The game2 stuff, that's trivial. I isolated the logic for reading the raw image sometimes last fall? So now we just call Game whatever = new Game("path to file, namely ISO, but I believe there is/was logic for reading gcm files that Laete  or earlier contributors (pre-GitHub) wrote. Project was originally written in Portuguese.. so that was a fun time, starting out. Talk about in over your head..

But now we read the title, ID, potentially anything that can be accessed via a specific address or byte offset) this includes disc ID (0x00, 0x01 for D2)

With CISO's they simply moved the files header a certain offset amount into the file, we account for this by checking the file extension, and skipping ahead in the filestream if necessary.

Ironing out small kinks, and bugs (leftover 'ghosts' from replaced and unremoved functions, or partial migrations. (Soooo much code repetition. The code was not written with D.R.Y. in mind, it was sopping wet lol) But hey, when it was published, it functioned. It did the thing and it did it well.. translation was not fully/automatically handled (users were introduced to a Portuguese labeled form, left to guess there way around to settings to try to change the language to English. Not ideal) and it only did one transfer at a time, no batches of files or queues to be spoken of.

It's been.. slower than I'd like, and honestly it would've been simpler and probably more efficient to start fresh with a more modern codebase/framework version i.e. .net core or w.e..

But community members had already invested so many real man hours into providing translations, that I would feel bad losing it/wasting it. I'm unsure how much of the specific translated string resources would be transferrable, or make sense, and that would basically tie one hand behind my back when creating a fresh project, trying to recreate the existing UI, instead of just doing what's most efficient/effective.

**Comment by sjohnson1021** [comment]
> From https://wit.wiimm.de/wit/#cmd
> <html>
> <body>
> 
> 
> ID6 | ID | Print ID6 of all found ISO files as simple list.
> -- | -- | --
> ID8 |   | Print ID6 + 2 next bytes as disc and version number of all found ISO files as simple list.
> 
> 
> </body>
> </html>
> 
> 
> Tested with Tales of Symphonia (2 discs) and Resident Evil 4 (2 discs + Bonus)
> Command: `wit ID6 .\path-to-game` and `wit ID8 .\path-to-game` 
> | Game | Disc | ID6 | ID8 |
> | ---      | ---   | ---  | ---  |
> | Tales of Symphonia (Spain) | Disc 1 | GQSSAF |  GQSSAF 00.00
> | Tales of Symphonia (Spain) | Disc 2 | GQSSAF |  GQSSAF 01.00
> | Resident Evil 4 (Europe) | Disc 1 | G4BP08 |  G4BP08 00.00
> | Resident Evil 4 (Europe) | Disc 2 | G4BP08 |  G4BP08 01.00
> | Resident Evil 4 (Europe) | Bonus Disc | D4BP01 | D4BP01 00.00
> 
> 

The existence of ID 8 potentially solves a quandary I had over a design choice. Whether to use a user preference to attempt to download specific language variants of applicable, falling back to general pal variant if a region specific cover isn't found. But. If I can just read which version of the game it actually is.. then, we would just download the CORRECT version, not necessarily the user's preference. I.e. if the game is Italian but the user has French selected.. it would technically be inaccurate to use the French version of the title. Cool to know.
