### ISSUE TITLE
Can't see network drives as a source folder

### ISSUE THREAD

**Issue by glitchwolfe** [AxionDrak/GameCube-Backup-Manager#8]
![Screenshot 2022-05-25 115536](https://user-images.githubusercontent.com/12235254/170346989-cf3d5728-b931-4a69-ae5e-181f3ed4db11.png)

I have all of my backups stored on a network drive (mapped as drive X in windows). Unfortunately the "Browse for folder" dialog box does not show this drive. Is there a workaround?

**Comment by sjohnson1021** [comment]
Will look into possibly using a different dialogue for the folder selection. Hypothetically an easy fix.

**Comment by sjohnson1021** [comment]
https://stackoverflow.com/questions/50905551/c-sharp-folder-browse-dialog-not-showing-network-shared-folders-win10

**Comment by sjohnson1021** [comment]
> ![Screenshot 2022-05-25 115536](https://user-images.githubusercontent.com/12235254/170346989-cf3d5728-b931-4a69-ae5e-181f3ed4db11.png)
> 
> I have all of my backups stored on a network drive (mapped as drive X in windows). Unfortunately the "Browse for folder" dialog box does not show this drive. Is there a workaround?

Try the latest update. Think I fixed it.
![Screenshot (24)](https://user-images.githubusercontent.com/8071133/177795869-f0ae2234-f719-4076-945e-64e7dfa801cf.png)

**Comment by flleeppyy** [comment]
I'm not seeing a Network item here, or any of my mapped drives
All of the media servers there just show video and music stuff.
![image](https://github.com/AxionDrak/GameCube-Backup-Manager/assets/18307183/599294f9-bf57-4957-93fe-01448fbc8e59)

**Comment by sjohnson1021** [comment]
@flleeppyy https://stackoverflow.com/questions/25892483/c-sharp-openfiledialog-is-not-showing-network-location-or-mapped-drive


Windows maps network locations on a user to user basis apparently, so.. because GCBM is running as admin (for.. drive access? I honestly am unsure of what code REQUIRES admin access, it has been brought up before and I believe laetemn had a response, but we aren't formatting drives or anything.. so?) mapped drives get lost.

The linked StackOverflow article has workarounds for forcing Window's admin account to see the mapped network locations, but this wouldn't be necessary if we were running the program as the user instead of launching with elevated permissions. 

Yet another reason for the rewrite.. I'd like to avoid requiring admin access, as I really don't see a need for it, outside of specific instances, and I know it's a security concern. I mean having the code open source and viewable/un-obfuscated should alleviate concerns, as there's nothing malicious, but. I know some people worry when they get asked to run as admin, or simply can't in some instances.

I could see about removing the 'run as admin' flag.. but my current dev environment is.. a Frankenstein-ed modified and partially rewritten version of the Git repo, and quarter/half-built Avalonia UI 11 project.. 

I want to look into it, but at the same time, it would take already limited time away from the rewrite which in and of itself is a learning process...

See if the workarounds listed in the StackOverflow post resolve the issue, if possible.. Sorry I don't have a better, immediate answer for you.

**Comment by flleeppyy** [comment]
Yep, More Directories does work but mapped drives don't show, and discovering network devices under the Network item takes about 5-10 minutes...
