### ISSUE TITLE
Translation Request/Offer: Simplified and Traditional Chinese.

### ISSUE THREAD

**Issue by sjohnson1021** [AxionDrak/GameCube-Backup-Manager#89]
Looking for someone to localize the project into Simplified and Traditional Chinese. It would be greatly appreciated.

@fei0316 has offered to do just that.
🙇 ❤️ 👍 

We use ResX Manager in Visual Studio, part of the benefit of this is the ability to export and import into an excel sheet format, making it easier for non developers to join in. I am also just learning of this feature:

<img width="1696" alt="Screenshot 2022-09-02 184923" src="https://user-images.githubusercontent.com/8071133/188247171-c741b98c-a8c8-4e28-b486-68134237088f.png">
 

So.. I'm going to launch a poll for which languages we would like to see. and give it a quick run through Google, as I do have a dev account active.. Not sure how much or how accurate it will do/be but better than nothing and worth a shot.

**Comment by fei0316** [comment]
Hi, I just started the translation but I found a weird wording in the other existing languages. Shouldn't this be "log data" not registry data? Since it's referring to clearing the logs.
![圖片](https://user-images.githubusercontent.com/8295915/188304869-9c5e3887-4126-4d7e-ae78-df3ca1c1287c.png)

**Comment by sjohnson1021** [comment]
Yes. Someone else asked about that, somewhere in the settings it says "Register Log" or something and people got concerned over security. It's simply refferring to the debug TXT log

**Comment by sjohnson1021** [comment]
So, "Log is already empty" or something similar would be more appropriate.

**Comment by sjohnson1021** [comment]
> Hi, I just started the translation but I found a weird wording in the other existing languages. Shouldn't this be "log data" not registry data? Since it's referring to clearing the logs. ![圖片](https://user-images.githubusercontent.com/8295915/188304869-9c5e3887-4126-4d7e-ae78-df3ca1c1287c.png)

Soo.. I'm almost ready to drop 2.6.1.0 , stability improvements, and such which won't effect the .resx files... BUT... .. ahem. I uh, also moved some labels, and added a checkbox. So.. There will be some conflicts, and it won't like an automatic merge. Just a heads up. Shouldn't be anything major, I just don't want you to pull a commit and have it overwrite your effort. I've done that. But you mentioned you're familiar with Git, so. Just thought I'd drop a heads up.

**Comment by fei0316** [comment]
Thanks for the heads up. I am still translating. 
One side note: I suggest removing the translation for the name of the languages in Settings (i.e. display the words "Portuguese", "Korean", etc. in Portuguese/Korean/etc.), so that people who chose a wrong language by accident can still go back and change it back easily.

**Comment by sjohnson1021** [comment]
> Thanks for the heads up. I am still translating. 
> One side note: I suggest removing the translation for the name of the languages in Settings (i.e. display the words "Portuguese", "Korean", etc. in Portuguese/Korean/etc.), so that people who chose a wrong language by accident can still go back and change it back easily.

Not sure if it's going to be beneficial or not, but I'm going to run through a few more languages with resx man's translate feature and Google's cloud translate API. (Might look into Baidu, would be ideal, or azure etc..) Chinese traditional and simplified being two on the list. I'm then going to add them to [this publicly editable Google Sheet.](https://docs.google.com/spreadsheets/d/1YyImjM7hPkJPdr_8nmBuiRnnrPzdmb2J/edit?usp=drivesdk&ouid=113862669718221596237&rtpof=true&sd=true)  

I'm hoping this will allow and possibly even encourage others to join in the efforts, with the full possibility of adding new languages, or narrowing down to specific dialects.

I'll run through probably 4 or 5 more languages this evening when I get back home. It's far from perfect, I know. Might even be worse than dealing with a foreign language in some cases, but it would at least provide a starting point for other languages to be added and improved.

Thanks again, gotta go stock up on caffeine and protein. 😂

> ## [Google Sheet - GCBM Localization Project ](https://docs.google.com/spreadsheets/d/1YyImjM7hPkJPdr_8nmBuiRnnrPzdmb2J/edit?usp=drivesdk&ouid=113862669718221596237&rtpof=true&sd=true)

**Comment by sjohnson1021** [comment]
Pushed a commit.. Swapped to DeepL for machine driven translations. they offered Simplified Chinese, so I took advantage of that and ran it through, along with a handful of other popular languages. I'm sure it's far from perfect. But thought I would give another heads up just in case. 2.6.1.2 should be out soon. with .. well .. basic support for Simplified chinese at least. Traditional was not available.. I don't trust Google translate for that, and I have yet to look into baidu.

**Comment by fei0316** [comment]
Sorry for the lack of replies recently. I've been busy with work and school lately so did not have much time to work on this. Just a heads up that I have not abandoned this and will continue with it soon.

**Comment by fei0316** [comment]
Hi, I just completed the translation and created a PR. It has Traditional Chinese hand translated myself and Simplified Chinese converted from Traditional using OpenCC with some proofreading. The differences between Traditional and Simplified Chinese are mainly in the way characters are written (mostly one-to-one and those that are not are handled by lookup tables that should cover >90% of cases) and some word choices (which OpenCC also deals with pretty well) so machine conversion is fine.

Regarding the use of DeepL or Google or Baidu translate for translating English/Portuguese to other languages, I would still advise against doing it unless machine translated languages are specially marked and not selected by default. Many strings in programs are just one word (e.g. "Files", "Processing...") and they might translate to a bunch of different words depending on the context which the translator would have no way of knowing. I do know that translating between Western/Latin-based languages is much more accurate than between say English and Japanese, but I don't know any other non-English Western languages so I'm not the one to say anything.

Finally, I identified the following small issues with the program that I thought might be worth noting here:

1. Since the program is licensed in the MIT License, I think we should replace "All Rights Reserved" in the program and installer, and note that it is licensed through the MIT License and provide a copy of the license, as required.
2. Fixed some English translation mistake by comparing to the Portuguese original
3. The information about the transfer methods might be wrong but I did not change it: Scrub should remove garbage not fill with zero, that's wipe. Let me know if I am correct or not and I can fix the Chinese translation if needed.
4. Logging part is a bit too confusing so I did not translate it yet, can you explain what do the features do? Also I can't seem to use the feature so I couldn't test what the options do either.

Anyway, thank you for developing the program and wish you a nice holiday!

**Comment by fei0316** [comment]
One more thing: I did not implement any logic that allows the two languages to be used (except adding them as resource file) and my PR does not delete any machine translated resources from the codebase. It's probably necessary to make some modifications (that I unfortunately cannot help as I have no experience with Windows development) before my translations can be used. My translated resources have the suffix `zh-TW` for Traditional (Taiwan) Chinese and `zh-CN` for Simplified (China) Chinese, compared to just `zh` in the machine translated ones.

**Comment by sjohnson1021** [comment]
> One more thing: I did not implement any logic that allows the two languages to be used (except adding them as resource file) and my PR does not delete any machine translated resources from the codebase. It's probably necessary to make some modifications (that I unfortunately cannot help as I have no experience with Windows development) before my translations can be used. My translated resources have the suffix `zh-TW` for Traditional (Taiwan) Chinese and `zh-CN` for Simplified (China) Chinese, compared to just `zh` in the machine translated ones.

Implemented in the latest releases. Thank you so much 😄
